name: cornyjokes 
adopt-info: cornyjokes
summary: Corny jokes for the terminal 
description: |
  Corny, clean jokes for the terminal.

grade: stable 
confinement: strict 
license: MIT
base: core22

apps:
  cornyjokes:
    command: bin/cornyjokes
    environment:
      LC_ALL: C.UTF-8
     
parts: 
  cornyjokes:
    source: https://github.com/kz6fittycent/corny-jokes
    source-type: git
    plugin: python
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
